# Generated by Django 3.2.6 on 2024-08-18 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="author",
            field=models.ForeignKey(
                help_text="автор объявления",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="создатель объявления",
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="время и дата создания объявления",
                verbose_name="время и дата создания объявления",
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="description",
            field=models.TextField(
                help_text="напишите описание товара", verbose_name="описание товара"
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="price",
            field=models.PositiveIntegerField(
                help_text="введите цену товара", verbose_name="цена товара"
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="title",
            field=models.CharField(
                help_text="напишите название товара",
                max_length=150,
                verbose_name="название товара",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="ad",
            field=models.ForeignKey(
                help_text="объявление, под которым оставлен отзыв",
                on_delete=django.db.models.deletion.CASCADE,
                to="ads.ad",
                verbose_name="объявление, под которым оставлен отзыв",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                help_text="автор отзыва",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="автор отзыва",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="время и дата создания отзыва",
                verbose_name="время и дата создания отзыва",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(
                help_text="напишите отзыв", verbose_name="текст отзыва"
            ),
        ),
    ]
