# Generated by Django 3.2.6 on 2024-08-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_auto_20240818_0845"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="загрузите изображение",
                null=True,
                upload_to="ads",
                verbose_name="Изображение",
            ),
        ),
    ]
